version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

jobs:
  test-node:
    docker:
      - image: cypress/browsers:latest  # Use the latest available image
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start the server
          command: |
            npm start &  # This will start the server in the background
            sleep 5      # Wait for the server to be up and running
      - cypress/install
      - run:
          name: Run Cypress tests
          command: npx cypress run --headless --browser chrome

  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node