version: 2.1

orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@3.4.0

jobs:
  test-node:
    docker:
      - image: cypress/browsers:latest  # Adjust the browser image as needed
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - cypress/install
      - run:
          name: Start the server
          command: |
            npm run start &  # Start the server in the background
            # Optionally check if the server is running before proceeding
            echo "Waiting for server to start on http://localhost:3000"
            npx wait-on http://localhost:3000  # This will block until the server is ready
      - run:
          name: Run Cypress tests
          command: npm run test  # Run your Cypress tests

  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node